### ISSUE TITLE
Feature request: Different max idle time when playing/not playing

### ISSUE THREAD

**Issue by Dis90** [b-jesch/service.sleepy.watchdog#10]
Hi,

Would be nice if user could set different max idle time for situation when playing video and when not playing video.

**Comment by b-jesch** [comment]
You mean if kodi itself is idle?

**Comment by Dis90** [comment]
Yep. Example if I'm in Kodi main menu it would be nice to have max idle time 15 min and when playing video max idle to 180 min.

**Comment by b-jesch** [comment]
I've implemented this in the new Matrix version 3.0.6+matrix. For Leia there's no intention to implement this.
