### ISSUE TITLE
Feature request: Option to disable idle timer while recording

### ISSUE THREAD

**Issue by Dis90** [b-jesch/service.sleepy.watchdog#11]
Can you add option to disable idle timer while pvr recording is active?

**Comment by b-jesch** [comment]
Makes sense.

**Comment by Dis90** [comment]
Maybe make it optional because not everyone has pvr backend in same machine with Kodi?

**Comment by b-jesch** [comment]
Yes, this is now an option and disabled by default. Changes are made in the new version 3.0.7+matrix.
