### ISSUE TITLE
Disable idle timer while SSH or Samba connection active

### ISSUE THREAD

**Issue by Dis90** [b-jesch/service.sleepy.watchdog#12]
Would be nice to have option to disable idle timer while SSH or Samba connection is active. Or would it be possible create own service for that?

Edit. maybe service like this but for Sleepy Watchdog https://github.com/Dis90/service.inhibit_shutdown

**Comment by b-jesch** [comment]
I don't think so. The main purpose of the addon is to monitor user (in)activity, not to monitor system events or status.

A service that checks user, recorder, network and process activity is the "PVR Recording & Power Manager" or in case that your system is mainly running as a (recoder) server: "Record & Power Manager Service NG²"

Maybe this is what you looking for. Note that the addons above cannot run at same time. Both addons are available in the "Nerds Repo": https://repo.kodinerds.net

**Comment by Dis90** [comment]
Thanks for reply, I understand.

I will check "PVR Recording & Power Manager" if that works better for my needs.
