### ISSUE TITLE
Permanent UnicodeDecodeError on non-english locale

### ISSUE THREAD

**Issue by WTFThatPerson** [b-jesch/service.sleepy.watchdog#13]
Leia 18.9 on Raspberry Pi
Kodi log is flooded of 
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
       - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
      Error Type: <type 'exceptions.UnicodeDecodeError'>
      Error Contents: 'ascii' codec can't decode byte 0xd0 in position 38: ordinal not in range(128)
      Traceback (most recent call last):
        File "/var/lib/kodi/.kodi/addons/service.sleepy.watchdog/default.py", line 42, in onNotification
          notifyLog('data:   %s' % (data))
        File "/var/lib/kodi/.kodi/addons/service.sleepy.watchdog/default.py", line 22, in notifyLog
          xbmc.log('[%s] %s' % (__addonname__, message.encode('utf-8')), level)
      UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 38: ordinal not in range(128)
```
Position changes according to current notification, but error remains the same.
Problem can be solved by adding
```
11 import sys
12 reload(sys)
13 sys.setdefaultencoding('utf8')
``` 
so it may be wise idea to add it permanently, in Leia branch at least, because I'm not sure it will work for Python 3

**Comment by b-jesch** [comment]
Please provide the version of the addon you're using.

**Comment by WTFThatPerson** [comment]
I'm sorry for delay to answer
addon ver 0.1.20 installed on Kodi 18.9
OS: Arch Linux Arm armv7l on Raspberry Pi3

**Comment by b-jesch** [comment]
Ups, this is indeed a very old version. Actually the version number stays at 0.1.36 (Leia). I guess you get the addon from the kodi repository. For personal reasons, I no longer distribute the addon through this repository. Please use the nerds repo instead:

https://repo.kodinerds.net

Btw. I have implemented your suggestions in the last version for Leia.
