### ISSUE TITLE
Cannot disable "keep alive"

### ISSUE THREAD

**Issue by Maiskolf** [b-jesch/service.sleepy.watchdog#15]
I'm running Sleepy Watchdog on Kodi 20.1. In the Kodi debug log, I see there is a setting that keeps the Idle timers alive even after it's action has been fired: `debug <general>: [service.sleepy.watchdog] Keep alive: True` . This results in the configured action (e.g. turn off the TV) to repeat over and over again.

In the addon's settings menu, I see no option to change or disable the "keep alive" parameter. In the "settings.xml" file under the addons_data folder, the option is included and set to True. When manually editing this file and setting this option to False, the option is again changed back to True the next time that Kodi is rebooted.

As I see it, there is currently no way to set this option persistently to False?

Log extract:
<details>

> 2023-04-12` 15:22:35.948 T:24880   debug <CAddonSettings[0@service.sleepy.watchdog]>: trying to load setting definitions from old format...
> 2023-04-12 15:22:35.950 T:24880   debug <CSettingsManager>: requested setting (mode) was not found.
> 2023-04-12 15:22:35.950 T:24880   debug <CSettingsManager>: requested setting (userIdleTime) was not found.
> 2023-04-12 15:22:35.954 T:24903   debug <general>: Thread JobWorker start, auto delete: true
> 2023-04-12 15:22:35.954 T:24880   debug <CAddonSettings[0@service.sleepy.watchdog]>: trying to load setting definitions from old format...
> 2023-04-12 15:22:35.956 T:24880   debug <CSettingsManager>: requested setting (mode) was not found.
> 2023-04-12 15:22:35.956 T:24880   debug <CSettingsManager>: requested setting (userIdleTime) was not found.
> 2023-04-12 15:22:35.964 T:24880   debug <general>: [service.sleepy.watchdog] settings (re)loaded...
> 2023-04-12 15:22:35.964 T:24880   debug <general>: [service.sleepy.watchdog] current mode:                   SERVICE
> 2023-04-12 15:22:35.964 T:24880   debug <general>: [service.sleepy.watchdog] silent mode:                    True
> 2023-04-12 15:22:35.965 T:24880   debug <general>: [service.sleepy.watchdog] message type:                   0
> 2023-04-12 15:22:35.965 T:24880   debug <general>: [service.sleepy.watchdog] Duration of notification:       60
> 2023-04-12 15:22:35.965 T:24880   debug <general>: [service.sleepy.watchdog] send CEC:                       False
> 2023-04-12 15:22:35.965 T:24880   debug <general>: [service.sleepy.watchdog] Time frame:                     0
> 2023-04-12 15:22:35.965 T:24880   debug <general>: [service.sleepy.watchdog] Activity start:                 75600
> 2023-04-12 15:22:35.965 T:24880   debug <general>: [service.sleepy.watchdog] Activity stop:                  21600
> 2023-04-12 15:22:35.966 T:24880   debug <general>: [service.sleepy.watchdog] Reset idle time on frame start: False
> 2023-04-12 15:22:35.966 T:24880   debug <general>: [service.sleepy.watchdog] max. idle time:                 900
> 2023-04-12 15:22:35.966 T:24880   debug <general>: [service.sleepy.watchdog] Menu idle time:                 300
> 2023-04-12 15:22:35.966 T:24880   debug <general>: [service.sleepy.watchdog] Idle time set by user:          900
> 2023-04-12 15:22:35.966 T:24880   debug <general>: [service.sleepy.watchdog] Check PVR recording activities: False
> 2023-04-12 15:22:35.966 T:24880   debug <general>: [service.sleepy.watchdog] Action:                         32135
> 2023-04-12 15:22:35.966 T:24880   debug <general>: [service.sleepy.watchdog] Jump to main menu:              False
> 2023-04-12 15:22:35.966 T:24880   debug <general>: [service.sleepy.watchdog] Keep alive:                     True
> 2023-04-12 15:22:35.966 T:24880   debug <general>: [service.sleepy.watchdog] Run addon:                      kodi.script.turnofflgtv
> 2023-04-12 15:22:35.967 T:24880   debug <general>: [service.sleepy.watchdog] Script type:                    0
> 2023-04-12 15:22:35.967 T:24880   debug <general>: [service.sleepy.watchdog] Load profile:                   
> 2023-04-12 15:22:35.967 T:24880   debug <general>: [service.sleepy.watchdog] Test configuration:             False
> 2023-04-12 15:22:35.967 T:24880   debug <general>: [service.sleepy.watchdog] Sleepy Watchdog kicks in (mode: SERVICE)
> 2023-04-12 15:22:35.967 T:24880   debug <general>: [service.sleepy.watchdog] Idle Time has changed: 300
> 2023-04-12 15:22:35.968 T:24880   debug <general>: [service.sleepy.watchdog] Watchdog status changed: active

</details>

**Comment by b-jesch** [comment]
Go into addon settings and set 'Action to execute' to 'Stop playing media'. The Option 'Keep WatchDog alive' is now visible. Turn this option off and switch back to your desired action. That should do the trick.

![Bildschirmfoto von 2023-04-12 18-09-48](https://user-images.githubusercontent.com/10152384/231518892-7b9d3a99-a50d-47d6-a951-42ddf1cdb566.png)

There are some code adjustments necessary.

**Comment by b-jesch** [comment]
Just pushed an update that set the option 'keep watchdog alive' to visible for the action 'Run Addon, Plugin or Script'. Available in Kodinerds Repo.

**Comment by Maiskolf** [comment]
Thank you @b-jesch , much much appreciated!
