### ISSUE TITLE
Watchdog warns its about to stop playback when nothing is being played

### ISSUE THREAD

**Issue by Chrunchy** [b-jesch/service.sleepy.watchdog#2]
I use OSMC on a fresh install.

Sleep watchdog has been installed. For testing purposes, i set the timer to 15 minutes.
However, when osmc isn't playing anything watchdog still shows up to warn that it's about to stop playback. Obviusly, nothing happens when the times has ended.

When media is playing, it works as intended and stops the media.

Is there any prerequisted for this addon to run proplerly?

**Comment by b-jesch** [comment]
After a long time this has been fixed now.
