### ISSUE TITLE
Kodi 19 support

### ISSUE THREAD

**Issue by giacomo892** [b-jesch/service.sleepy.watchdog#9]
Hello. The add-on doesn't work on Kodi 19 matrix.

**Comment by b-jesch** [comment]
Please provide a debug log and describe the in more detail. Do You use the right version for matrix (3.0.3+matrix)?

**Comment by giacomo892** [comment]
Hello.
Can you point me out where I can get that version? Then I can try it and report.

**Comment by b-jesch** [comment]
Install the Kodinerds Addon Repo (https://repo.kodinerds.net) and install the Sleepy Watchdog from this repo. You could also direct download and install from ZIP, but with this method you don't receive any updates.

**Comment by giacomo892** [comment]
Ok done and it is working fine. Thanks
Any particular reason why update is not on main Kodi repo?

**Comment by b-jesch** [comment]
There are some personal reasons.
